### ISSUE TITLE
support for 1.15.2

### ISSUE THREAD

**Issue by FunWithFlaggs** [polyvalord/extcaves#14]
Forge loads the mod, but reports "Extended Caves (extcaves) encountered an error during the common_setup event phase"

this is out of the logfile:

`[modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid extcaves
java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_222280_a(Lnet/minecraft/world/gen/feature/Feature;Lnet/minecraft/world/gen/feature/IFeatureConfig;Lnet/minecraft/world/gen/placement/Placement;Lnet/minecraft/world/gen/placement/IPlacementConfig;)Lnet/minecraft/world/gen/feature/ConfiguredFeature;
	at com.polyvalord.extcaves.world.GenPreFeatures.setupPreFeaturesGen(GenPreFeatures.java:26) ~[?:1.5]
	at com.polyvalord.extcaves.ExtCaves.setup(ExtCaves.java:75) ~[?:1.5]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]`

i guess the main issue is
`java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_222280_a`

If i can help with this just tell me :)

**Comment by polyvalord** [comment]
Did you try with forge 1.15 ? Because it's not compatible for now.

**Comment by FunWithFlaggs** [comment]
with 1.15.2-forge-31.2.0
What do you mean is not compatible? this mod with forge or this mod with minecraft 1.15.2?

**Comment by Reden1471** [comment]
I have this error message too... I've just installed the "release 1.15.2-forge-32.1.0" (it's the recommended version by forge) and it don't work with that
